---
- hosts: web

  tasks:
    - include_vars: vars/proj_vars.yml

    - name: Install docker
      yum: name=docker state=latest

    - name: Install python-docker-py
      yum: name=python-docker-py state=latest

    - name: Make sure a service unit is running
      ansible.builtin.systemd: state=started name=docker

#    - name: Enable service docker and ensure it is not masked
#      ansible.builtin.systemd: name=docker enabled=yes masked=no

#    - name: Enable service containerd and ensure it is not masked
#      ansible.builtin.systemd: name=containerd enabled=yes masked=no

    - name: Print remote project dir
      debug: var=remote_install_path

    - name: Create build directory
      ansible.builtin.file:
        path: "{{ remote_install_path }}"
        state: directory
        mode: '0755'

    - name: Copy project to remote server
      ansible.builtin.copy: src="../docker/" dest="{{ remote_install_path }}"

    - debug: var=app_image_name

    - name: Build container image
      docker_image:
        name: "{{ app_image_name }}"
        debug: yes
        build:
          path: "{{ remote_install_path }}"
        source: build
        state: present

    - debug: var=app_container_name

    - name: Build container image
      docker_container:
        name: "{{ app_container_name }}"
        image: "{{ app_image_name }}"
        state: started
        ports:
          "8081:8081" 

